name: dash_desercion
channels:
  - conda-forge
dependencies:
  - python=3.11
  - dash
  - dash-bootstrap-components
  - pandas
  - geopandas
  - plotly
  - numpy
  - matplotlib
  - seaborn
  - unidecode
  - gunicorn
